//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Competence resource.
    /// </summary>
    //  *** Start programmer edit section *** (CompetenceResource CustomAttributes)

    //  *** End programmer edit section *** (CompetenceResource CustomAttributes)
    [AutoAltered()]
    [Caption("Competence resource")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CompetenceResourceE", new string[] {
            "Level as \'Уровень владения\'",
            "Resource as \'Ресурс\'",
            "Resource.Name as \'Name\'"}, Hidden=new string[] {
            "Resource.Name"})]
    [MasterViewDefineAttribute("CompetenceResourceE", "Resource", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class CompetenceResource : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CMS.CompetenceLevel fLevel;
        
        private IIS.CMS.Resource fResource;
        
        private IIS.CMS.Competence fCompetence;
        
        //  *** Start programmer edit section *** (CompetenceResource CustomMembers)

        //  *** End programmer edit section *** (CompetenceResource CustomMembers)

        
        /// <summary>
        /// Level.
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceResource.Level CustomAttributes)

        //  *** End programmer edit section *** (CompetenceResource.Level CustomAttributes)
        public virtual IIS.CMS.CompetenceLevel Level
        {
            get
            {
                //  *** Start programmer edit section *** (CompetenceResource.Level Get start)

                //  *** End programmer edit section *** (CompetenceResource.Level Get start)
                IIS.CMS.CompetenceLevel result = this.fLevel;
                //  *** Start programmer edit section *** (CompetenceResource.Level Get end)

                //  *** End programmer edit section *** (CompetenceResource.Level Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (CompetenceResource.Level Set start)

                //  *** End programmer edit section *** (CompetenceResource.Level Set start)
                this.fLevel = value;
                //  *** Start programmer edit section *** (CompetenceResource.Level Set end)

                //  *** End programmer edit section *** (CompetenceResource.Level Set end)
            }
        }
        
        /// <summary>
        /// Competence resource.
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceResource.Resource CustomAttributes)

        //  *** End programmer edit section *** (CompetenceResource.Resource CustomAttributes)
        [NotNull()]
        public virtual IIS.CMS.Resource Resource
        {
            get
            {
                //  *** Start programmer edit section *** (CompetenceResource.Resource Get start)

                //  *** End programmer edit section *** (CompetenceResource.Resource Get start)
                IIS.CMS.Resource result = this.fResource;
                //  *** Start programmer edit section *** (CompetenceResource.Resource Get end)

                //  *** End programmer edit section *** (CompetenceResource.Resource Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (CompetenceResource.Resource Set start)

                //  *** End programmer edit section *** (CompetenceResource.Resource Set start)
                this.fResource = value;
                //  *** Start programmer edit section *** (CompetenceResource.Resource Set end)

                //  *** End programmer edit section *** (CompetenceResource.Resource Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CMS.Competence.
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceResource.Competence CustomAttributes)

        //  *** End programmer edit section *** (CompetenceResource.Competence CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CMS.Competence Competence
        {
            get
            {
                //  *** Start programmer edit section *** (CompetenceResource.Competence Get start)

                //  *** End programmer edit section *** (CompetenceResource.Competence Get start)
                IIS.CMS.Competence result = this.fCompetence;
                //  *** Start programmer edit section *** (CompetenceResource.Competence Get end)

                //  *** End programmer edit section *** (CompetenceResource.Competence Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (CompetenceResource.Competence Set start)

                //  *** End programmer edit section *** (CompetenceResource.Competence Set start)
                this.fCompetence = value;
                //  *** Start programmer edit section *** (CompetenceResource.Competence Set end)

                //  *** End programmer edit section *** (CompetenceResource.Competence Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CompetenceResourceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompetenceResourceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompetenceResourceE", typeof(IIS.CMS.CompetenceResource));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of CompetenceResource.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfCompetenceResource CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfCompetenceResource CustomAttributes)
    public class DetailArrayOfCompetenceResource : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CMS.DetailArrayOfCompetenceResource members)

        //  *** End programmer edit section *** (IIS.CMS.DetailArrayOfCompetenceResource members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type CompetenceResource by index.
        /// </summary>
        /// <summary>
        /// Adds object with type CompetenceResource.
        /// </summary>
        public DetailArrayOfCompetenceResource(IIS.CMS.Competence fCompetence) : 
                base(typeof(CompetenceResource), ((ICSSoft.STORMNET.DataObject)(fCompetence)))
        {
        }
        
        public IIS.CMS.CompetenceResource this[int index]
        {
            get
            {
                return ((IIS.CMS.CompetenceResource)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CMS.CompetenceResource dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
