//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CMS
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Competence level.
    /// </summary>
    //  *** Start programmer edit section *** (CompetenceLevel CustomAttributes)

    //  *** End programmer edit section *** (CompetenceLevel CustomAttributes)
    public enum CompetenceLevel
    {
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceLevel.Basic CustomAttributes)

        //  *** End programmer edit section *** (CompetenceLevel.Basic CustomAttributes)
        Basic,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceLevel.Intermediate CustomAttributes)

        //  *** End programmer edit section *** (CompetenceLevel.Intermediate CustomAttributes)
        Intermediate,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (CompetenceLevel.Advanced CustomAttributes)

        //  *** End programmer edit section *** (CompetenceLevel.Advanced CustomAttributes)
        Advanced,
    }
}
