//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Competence.
    /// </summary>
    //  *** Start programmer edit section *** (Competence CustomAttributes)

    //  *** End programmer edit section *** (Competence CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CompetenceE", new string[] {
            "Name as \'Наименование\'"})]
    [AssociatedDetailViewAttribute("CompetenceE", "CompetenceResource", "CompetenceResourceE", true, "", "Ресурсы для изучения", true, new string[] {
            ""})]
    [View("CompetenceL", new string[] {
            "Name as \'Name\'"})]
    public class Competence : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.CMS.DetailArrayOfCompetenceResource fCompetenceResource;
        
        //  *** Start programmer edit section *** (Competence CustomMembers)

        //  *** End programmer edit section *** (Competence CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Competence.Name CustomAttributes)

        //  *** End programmer edit section *** (Competence.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Competence.Name Get start)

                //  *** End programmer edit section *** (Competence.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Competence.Name Get end)

                //  *** End programmer edit section *** (Competence.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Competence.Name Set start)

                //  *** End programmer edit section *** (Competence.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Competence.Name Set end)

                //  *** End programmer edit section *** (Competence.Name Set end)
            }
        }
        
        /// <summary>
        /// Competence.
        /// </summary>
        //  *** Start programmer edit section *** (Competence.CompetenceResource CustomAttributes)

        //  *** End programmer edit section *** (Competence.CompetenceResource CustomAttributes)
        public virtual IIS.CMS.DetailArrayOfCompetenceResource CompetenceResource
        {
            get
            {
                //  *** Start programmer edit section *** (Competence.CompetenceResource Get start)

                //  *** End programmer edit section *** (Competence.CompetenceResource Get start)
                if ((this.fCompetenceResource == null))
                {
                    this.fCompetenceResource = new IIS.CMS.DetailArrayOfCompetenceResource(this);
                }
                IIS.CMS.DetailArrayOfCompetenceResource result = this.fCompetenceResource;
                //  *** Start programmer edit section *** (Competence.CompetenceResource Get end)

                //  *** End programmer edit section *** (Competence.CompetenceResource Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Competence.CompetenceResource Set start)

                //  *** End programmer edit section *** (Competence.CompetenceResource Set start)
                this.fCompetenceResource = value;
                //  *** Start programmer edit section *** (Competence.CompetenceResource Set end)

                //  *** End programmer edit section *** (Competence.CompetenceResource Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CompetenceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompetenceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompetenceE", typeof(IIS.CMS.Competence));
                }
            }
            
            /// <summary>
            /// "CompetenceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompetenceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompetenceL", typeof(IIS.CMS.Competence));
                }
            }
        }
    }
}
