//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource.
    /// </summary>
    //  *** Start programmer edit section *** (Resource CustomAttributes)

    //  *** End programmer edit section *** (Resource CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ResourceE", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "Link as \'Link\'"})]
    [View("ResourceL", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "Link as \'Link\'"})]
    public class Resource : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fDescription;
        
        private string fLink;
        
        //  *** Start programmer edit section *** (Resource CustomMembers)

        //  *** End programmer edit section *** (Resource CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Resource.Name CustomAttributes)

        //  *** End programmer edit section *** (Resource.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Resource.Name Get start)

                //  *** End programmer edit section *** (Resource.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Resource.Name Get end)

                //  *** End programmer edit section *** (Resource.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Resource.Name Set start)

                //  *** End programmer edit section *** (Resource.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Resource.Name Set end)

                //  *** End programmer edit section *** (Resource.Name Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        //  *** Start programmer edit section *** (Resource.Description CustomAttributes)

        //  *** End programmer edit section *** (Resource.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                //  *** Start programmer edit section *** (Resource.Description Get start)

                //  *** End programmer edit section *** (Resource.Description Get start)
                string result = this.fDescription;
                //  *** Start programmer edit section *** (Resource.Description Get end)

                //  *** End programmer edit section *** (Resource.Description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Resource.Description Set start)

                //  *** End programmer edit section *** (Resource.Description Set start)
                this.fDescription = value;
                //  *** Start programmer edit section *** (Resource.Description Set end)

                //  *** End programmer edit section *** (Resource.Description Set end)
            }
        }
        
        /// <summary>
        /// Link.
        /// </summary>
        //  *** Start programmer edit section *** (Resource.Link CustomAttributes)

        //  *** End programmer edit section *** (Resource.Link CustomAttributes)
        [StrLen(255)]
        public virtual string Link
        {
            get
            {
                //  *** Start programmer edit section *** (Resource.Link Get start)

                //  *** End programmer edit section *** (Resource.Link Get start)
                string result = this.fLink;
                //  *** Start programmer edit section *** (Resource.Link Get end)

                //  *** End programmer edit section *** (Resource.Link Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Resource.Link Set start)

                //  *** End programmer edit section *** (Resource.Link Set start)
                this.fLink = value;
                //  *** Start programmer edit section *** (Resource.Link Set end)

                //  *** End programmer edit section *** (Resource.Link Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ResourceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ResourceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ResourceE", typeof(IIS.CMS.Resource));
                }
            }
            
            /// <summary>
            /// "ResourceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ResourceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ResourceL", typeof(IIS.CMS.Resource));
                }
            }
        }
    }
}
